name: Laboratoires Sion Dev CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine image tag
        id: vars
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/laboratoiresion-training-comm-${BRANCH_NAME}:latest"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_TAG

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy docker-compose.yml to VPS
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/github/laboratoiresion-training-comm/docker-compose.yml

      - name: Deploy And Cleanup Old Containers
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            export BRANCH_NAME=$(echo ${GITHUB_REF##*/}) &&
            docker stop laboratoiresion-training-comm-${BRANCH_NAME} || true
            docker rm laboratoiresion-training-comm-${BRANCH_NAME} || true
            cd /home/github/laboratoiresion-training-comm &&
            echo 'ðŸ”¹ Pulling latest image...'
            docker compose pull web &&
            echo 'ðŸ”¹ Restarting container...'
            docker compose up -d --remove-orphans &&
            echo 'âœ… Deployment completed.'"
